In [1]:
import pandas as pd
import os
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
!pwd

/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out

In [3]:
def find_emotions(folder_path):

#     folder_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/english/"
    # english_pretrain = pd.read_csv(file_path)

    dataframes = []

    # Iterate over all files in the folder
    for filename in os.listdir(folder_path):
        # Check if the file is a CSV file
        if filename.endswith(".csv"):
            # Construct the file path
            file_path = os.path.join(folder_path, filename)
            # Load the CSV file into a DataFrame
            df = pd.read_csv(file_path)
            # Append the DataFrame to the list
            dataframes.append(df)

    # Concatenate all DataFrames into one
    combined_df = pd.concat(dataframes, ignore_index=True)

    # Now you can work with the combined DataFrame
    combined_df.rename( columns={'Unnamed: 0':'group'}, inplace=True )
    combined_df = combined_df.iloc[:, 1:]
    return combined_df.mean(0)

In [4]:
def find_race(folder_path):
    file_path = os.path.join(folder_path, "race.csv")
    df = pd.read_csv(file_path)
    df.rename(columns={'Unnamed: 0':'group'}, inplace=True)
    df = df.iloc[:, 1:]
    return df.mean(0)

In [5]:
def find_minor(folder_path):
    file_path = os.path.join(folder_path, "racial_minorities.csv")
    df = pd.read_csv(file_path)
    df.rename(columns={'Unnamed: 0':'group'}, inplace=True)
    df = df.iloc[:, 1:]
    return df.mean(0)

In [6]:
english_pretrain_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/english/"
french_pretrain_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/french/"
spanish_pretrain_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/spanish/"
greek_pretrain_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/greek/"
croatian_pretrain_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/croatian/"



english_pretrain = find_emotions(english_pretrain_path)
french_pretrain = find_emotions(french_pretrain_path)
spanish_pretrain = find_emotions(spanish_pretrain_path)
greek_pretrain = find_emotions(greek_pretrain_path)
croatian_pretrain = find_emotions(croatian_pretrain_path)

In [7]:
# to obtain race

english_pretrain_race = find_race(english_pretrain_path)
french_pretrain_race = find_race(french_pretrain_path)
spanish_pretrain_race = find_race(spanish_pretrain_path)
greek_pretrain_race = find_race(greek_pretrain_path)
croatian_pretrain_race = find_race(croatian_pretrain_path)

In [8]:
# to obtain racial minorities 

english_pretrain_minor = find_minor(english_pretrain_path)
french_pretrain_minor = find_minor(french_pretrain_path)
spanish_pretrain_minor = find_minor(spanish_pretrain_path)
greek_pretrain_minor = find_minor(greek_pretrain_path)
croatian_pretrain_minor = find_minor(croatian_pretrain_path)

In [9]:
df_pretrain = pd.concat([english_pretrain, french_pretrain, spanish_pretrain, greek_pretrain, croatian_pretrain],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(df_pretrain.columns, new_column_names)}
df_pretrain = df_pretrain.rename(columns=column_mapping).transpose()
df_pretrain = df_pretrain.div(df_pretrain.sum(axis=1), axis=0)

In [10]:
df_pretrain

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,0.091499,0.052753,0.070844,0.123382,0.063267,0.191673,0.175232,0.082658,0.037334,0.111357
French,0.065825,0.060510,0.049007,0.088143,0.078099,0.157333,0.237769,0.063747,0.049508,0.150059
Spanish,0.057329,0.057579,0.048724,0.081867,0.086791,0.126998,0.272806,0.058903,0.045279,0.163725
Greek,0.065122,0.121713,0.009842,0.057290,0.077925,0.120414,0.292777,0.034187,0.039180,0.181551
Croatian,0.075367,0.068228,0.053779,0.085813,0.074653,0.158792,0.241312,0.054013,0.029344,0.158699

In [11]:
# for race

df_pretrain_race = pd.concat([english_pretrain_race, french_pretrain_race, spanish_pretrain_race, greek_pretrain_race, croatian_pretrain_race],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(df_pretrain_race.columns, new_column_names)}
df_pretrain_race = df_pretrain_race.rename(columns=column_mapping).transpose()
df_pretrain_race = df_pretrain_race.div(df_pretrain_race.sum(axis=1), axis=0)

In [12]:
# for minority

df_pretrain_minor = pd.concat([english_pretrain_minor, french_pretrain_minor, spanish_pretrain_minor, greek_pretrain_minor, croatian_pretrain_minor],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(df_pretrain_minor.columns, new_column_names)}
df_pretrain_minor = df_pretrain_minor.rename(columns=column_mapping).transpose()
df_pretrain_minor = df_pretrain_minor.div(df_pretrain_minor.sum(axis=1), axis=0)

## For English Finetuning

In [13]:
## For English finetuning

english_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/finetuned_stereoset_english/emotion_profiles/english/"
french_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/finetuned_stereoset_english/emotion_profiles/french/"
spanish_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/finetuned_stereoset_english/emotion_profiles/spanish/"
greek_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/finetuned_stereoset_english/emotion_profiles/greek/"
croatian_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/finetuned_stereoset_english/emotion_profiles/croatian/"



english_finetune = find_emotions(english_path)
french_finetune = find_emotions(french_path)
spanish_finetune = find_emotions(spanish_path)
greek_finetune = find_emotions(greek_path)
croatian_finetune = find_emotions(croatian_path)

english_finetune = english_finetune.div(english_finetune.sum())
french_finetune = french_finetune.div(french_finetune.sum())
spanish_finetune = spanish_finetune.div(spanish_finetune.sum())
greek_finetune = greek_finetune.div(greek_finetune.sum())
croatian_finetune = croatian_finetune.div(croatian_finetune.sum())

In [14]:
# to obtain race

english_finetune_race = find_race(english_path)
french_finetune_race = find_race(french_path)
spanish_finetune_race = find_race(spanish_path)
greek_finetune_race = find_race(greek_path)
croatian_finetune_race = find_race(croatian_path)


english_finetune_race = english_finetune_race.div(english_finetune_race.sum())
french_finetune_race = french_finetune_race.div(french_finetune_race.sum())
spanish_finetune_race = spanish_finetune_race.div(spanish_finetune_race.sum())
greek_finetune_race = greek_finetune_race.div(greek_finetune_race.sum())
croatian_finetune_race = croatian_finetune_race.div(croatian_finetune_race.sum())

In [15]:
# to obtain racial minorities 

english_finetune_minor = find_minor(english_path)
french_finetune_minor = find_minor(french_path)
spanish_finetune_minor = find_minor(spanish_path)
greek_finetune_minor = find_minor(greek_path)
croatian_finetune_minor = find_minor(croatian_path)


english_finetune_minor = english_finetune_minor.div(english_finetune_minor.sum())
french_finetune_minor = french_finetune_minor.div(french_finetune_minor.sum())
spanish_finetune_minor = spanish_finetune_minor.div(spanish_finetune_minor.sum())
greek_finetune_minor = greek_finetune_minor.div(greek_finetune_minor.sum())
croatian_finetune_minor = croatian_finetune_minor.div(croatian_finetune_minor.sum())

In [16]:
english_diff = english_finetune - english_pretrain_race
french_diff = spanish_finetune-french_pretrain_race
spanish_diff = spanish_finetune-spanish_pretrain_race
greek_diff = greek_finetune-greek_pretrain_race
croatian_diff =  croatian_finetune- croatian_pretrain_race

In [17]:
# race diff

english_diff_race = english_finetune_race - english_pretrain_race
french_diff_race = spanish_finetune_race-french_pretrain_race
spanish_diff_race = spanish_finetune_race-spanish_pretrain_race
greek_diff_race = greek_finetune_race-greek_pretrain_race
croatian_diff_race =  croatian_finetune_race- croatian_pretrain_race

In [18]:
# minor diff

english_diff_minor = english_finetune_minor - english_pretrain_minor
french_diff_minor = spanish_finetune_minor-french_pretrain_minor
spanish_diff_minor = spanish_finetune_minor-spanish_pretrain_minor
greek_diff_minor = greek_finetune_minor-greek_pretrain_minor
croatian_diff_minor =  croatian_finetune_minor- croatian_pretrain_minor

In [19]:
diff_finetune_english = pd.concat([english_diff, french_diff, spanish_diff, greek_diff, croatian_diff],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_english.columns, new_column_names)}
diff_finetune_english = diff_finetune_english.rename(columns=column_mapping).transpose()

In [20]:
# for race

diff_finetune_english_race = pd.concat([english_diff_race, french_diff_race, spanish_diff_race, greek_diff_race, croatian_diff_race],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_english_race.columns, new_column_names)}
diff_finetune_english_race = diff_finetune_english_race.rename(columns=column_mapping).transpose()

In [21]:
# for minor

diff_finetune_english_minor = pd.concat([english_diff_minor, french_diff_minor, spanish_diff_minor, greek_diff_minor, croatian_diff_minor],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_english_minor.columns, new_column_names)}
diff_finetune_english_minor = diff_finetune_english_minor.rename(columns=column_mapping).transpose()

In [22]:
diff_finetune_english

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-0.012748,-0.017537,-0.001918,-0.022251,-0.056585,-0.024026,-0.073351,-0.024247,-0.007553,-0.018786
French,0.000033,0.015488,-0.003680,-0.013180,-0.045534,-0.018522,-0.039983,-0.027061,-0.011586,-0.014666
Spanish,0.008797,0.018083,-0.004933,-0.003276,-0.049666,0.022396,-0.087266,-0.012379,-0.006877,-0.031392
Greek,0.023027,-0.052425,0.074792,0.065469,0.001981,0.164361,-0.111600,0.043511,0.035435,-0.103971
Croatian,0.026010,0.029882,-0.018570,-0.008161,-0.007315,0.022699,-0.010537,0.034170,0.017289,-0.023928

In [23]:
diff_finetune_english_perc = (diff_finetune_english/df_pretrain)*100

In [24]:
diff_finetune_english_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-13.932827,-33.244216,-2.707444,-18.034139,-89.437734,-12.535124,-41.859546,-29.333757,-20.230978,-16.869612
French,0.050706,25.595529,-7.509493,-14.952889,-58.303910,-11.772766,-16.815704,-42.451557,-23.401975,-9.773513
Spanish,15.344862,31.405221,-10.124885,-4.001486,-57.225670,17.635131,-31.988379,-21.015677,-15.186888,-19.173389
Greek,35.360173,-43.072753,759.965796,114.276148,2.542128,136.496226,-38.117898,127.273878,90.443185,-57.268153
Croatian,34.511315,43.797474,-34.530368,-9.510251,-9.799216,14.295108,-4.366489,63.261226,58.918240,-15.077597

In [25]:
diff_finetune_english_perc_race = (diff_finetune_english_race/df_pretrain_race)*100

In [26]:
diff_finetune_english_perc_race

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-12.054163,-37.239636,3.730535,-14.253838,-80.652362,-12.257596,-47.466540,-27.023608,-18.218316,-24.191909
French,0.613349,29.626550,-7.548135,-15.046593,-50.633436,-12.073398,-17.705057,-39.895882,-20.195915,-11.857821
Spanish,15.337961,35.400611,-9.719982,-4.894536,-52.661899,16.760640,-32.326790,-22.369477,-11.821801,-21.394309
Greek,36.855631,-48.884810,703.254322,113.578234,-10.161347,158.030469,-46.079706,159.527037,108.557591,-51.663131
Croatian,37.800618,40.132215,-23.021804,-6.881803,-10.995323,16.297699,-6.039015,70.495102,73.719647,-17.944827

In [27]:
diff_finetune_english_perc_minor = (diff_finetune_english_minor/df_pretrain_minor)*100

In [28]:
diff_finetune_english_perc_minor

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-32.697894,-39.463746,-13.860790,-31.103042,-86.123321,-28.466499,-53.452577,-39.677612,-19.313242,-31.628062
French,-10.793387,30.303569,-19.330375,-21.360684,-44.857808,-19.636501,-8.070004,-48.794184,-20.052207,2.576334
Spanish,-3.425178,38.491221,-21.508087,-17.082504,-52.824846,4.376500,-31.905249,-36.688043,-10.896086,-20.328642
Greek,68.899440,-54.236051,684.209882,156.591456,-19.069456,197.086435,-47.499132,125.097896,91.676884,-58.293826
Croatian,24.054411,59.834247,-25.491507,-13.508319,-8.086706,12.174482,-3.021945,45.232650,69.724426,-13.597993

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_english_perc.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_english_perc.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_english = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_english

           English    French   Spanish     Greek  Croatian
English   1.000000  0.760816  0.661147 -0.088587 -0.281214
French    0.760816  1.000000  0.851686 -0.244102 -0.202686
Spanish   0.661147  0.851686  1.000000 -0.125919  0.140656
Greek    -0.088587 -0.244102 -0.125919  1.000000 -0.130656
Croatian -0.281214 -0.202686  0.140656 -0.130656  1.000000

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_english_perc_race.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_english_perc_race.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_english_race = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_english_race

           English    French   Spanish     Greek  Croatian
English   1.000000  0.666611  0.594984 -0.018830 -0.280299
French    0.666611  1.000000  0.857716 -0.280510 -0.220632
Spanish   0.594984  0.857716  1.000000 -0.121635  0.123795
Greek    -0.018830 -0.280510 -0.121635  1.000000  0.060609
Croatian -0.280299 -0.220632  0.123795  0.060609  1.000000

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_english_perc_minor.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_english_perc_minor.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_english_minor = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_english_minor

           English    French   Spanish     Greek  Croatian
English   1.000000  0.638004  0.660411 -0.206387 -0.308898
French    0.638004  1.000000  0.861476 -0.466314 -0.123660
Spanish   0.660411  0.861476  1.000000 -0.308124  0.144930
Greek    -0.206387 -0.466314 -0.308124  1.000000 -0.066956
Croatian -0.308898 -0.123660  0.144930 -0.066956  1.000000

In [32]:
row_index1 = 0
row_index2 = 1
row_index3 = 2
row_index4 = 3

# Get the rows as NumPy arrays
row1 = diff_finetune_english_perc.iloc[row_index1].values.reshape(1, -1)
row2 = diff_finetune_english_perc.iloc[row_index2].values.reshape(1, -1)
row3 = diff_finetune_english_perc.iloc[row_index3].values.reshape(1, -1)
row4 = diff_finetune_english_perc.iloc[row_index4].values.reshape(1, -1)

# Calculate the cosine similarity between the two rows
similarity = cosine_similarity(row1, row2)[0, 0]
similarity2 = cosine_similarity(row1, row3)[0, 0]
print("Similarity between english and french is:  ", similarity)
print("Similarity between english and spanish is:  ", similarity2)

Similarity between english and french is:   0.7608160553093701
Similarity between english and spanish is:   0.6611472992299985

## French Fine-tuning

In [33]:
## For French finetuning

english_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/french_finetune/emotion_profiles/english/"
french_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/french_finetune/emotion_profiles/french/"
spanish_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/french_finetune/emotion_profiles/spanish/"
greek_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/french_finetune/emotion_profiles/greek/"
croatian_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/french_finetune/emotion_profiles/croatian/"



english_finetune = find_emotions(english_path)
french_finetune = find_emotions(french_path)
spanish_finetune = find_emotions(spanish_path)
greek_finetune = find_emotions(greek_path)
croatian_finetune = find_emotions(croatian_path)

english_finetune = english_finetune.div(english_finetune.sum())
french_finetune = french_finetune.div(french_finetune.sum())
spanish_finetune = spanish_finetune.div(spanish_finetune.sum())
greek_finetune = greek_finetune.div(greek_finetune.sum())
croatian_finetune = croatian_finetune.div(croatian_finetune.sum())

In [34]:
# to obtain race

english_finetune_race = find_race(english_path)
french_finetune_race = find_race(french_path)
spanish_finetune_race = find_race(spanish_path)
greek_finetune_race = find_race(greek_path)
croatian_finetune_race = find_race(croatian_path)

english_finetune_race = english_finetune_race.div(english_finetune_race.sum())
french_finetune_race = french_finetune_race.div(french_finetune_race.sum())
spanish_finetune_race = spanish_finetune_race.div(spanish_finetune_race.sum())
greek_finetune_race = greek_finetune_race.div(greek_finetune_race.sum())
croatian_finetune_race = croatian_finetune_race.div(croatian_finetune_race.sum())

In [35]:
# to obtain racial minorities 

english_finetune_minor = find_minor(english_path)
french_finetune_minor = find_minor(french_path)
spanish_finetune_minor = find_minor(spanish_path)
greek_finetune_minor = find_minor(greek_path)
croatian_finetune_minor = find_minor(croatian_path)


english_finetune_minor = english_finetune_minor.div(english_finetune_minor.sum())
french_finetune_minor = french_finetune_minor.div(french_finetune_minor.sum())
spanish_finetune_minor = spanish_finetune_minor.div(spanish_finetune_minor.sum())
greek_finetune_minor = greek_finetune_minor.div(greek_finetune_minor.sum())
croatian_finetune_minor = croatian_finetune_minor.div(croatian_finetune_minor.sum())

In [36]:
english_diff = english_finetune - english_pretrain
french_diff = spanish_finetune-french_pretrain
spanish_diff = spanish_finetune-spanish_pretrain
greek_diff = greek_finetune-greek_pretrain
croatian_diff =  croatian_finetune- croatian_pretrain

In [37]:
# race diff

english_diff_race = english_finetune_race - english_pretrain_race
french_diff_race = spanish_finetune_race-french_pretrain_race
spanish_diff_race = spanish_finetune_race-spanish_pretrain_race
greek_diff_race = greek_finetune_race-greek_pretrain_race
croatian_diff_race =  croatian_finetune_race- croatian_pretrain_race

In [38]:
# minor diff

english_diff_minor = english_finetune_minor - english_pretrain_minor
french_diff_minor = spanish_finetune_minor-french_pretrain_minor
spanish_diff_minor = spanish_finetune_minor-spanish_pretrain_minor
greek_diff_minor = greek_finetune_minor-greek_pretrain_minor
croatian_diff_minor =  croatian_finetune_minor- croatian_pretrain_minor

In [39]:
diff_finetune_french = pd.concat([english_diff, french_diff, spanish_diff, greek_diff, croatian_diff],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_french.columns, new_column_names)}
diff_finetune_french = diff_finetune_french.rename(columns=column_mapping).transpose()

In [40]:
# for race

diff_finetune_french_race = pd.concat([english_diff_race, french_diff_race, spanish_diff_race, greek_diff_race, croatian_diff_race],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_french_race.columns, new_column_names)}
diff_finetune_french_race = diff_finetune_french_race.rename(columns=column_mapping).transpose()

In [41]:
# for minor

diff_finetune_french_minor = pd.concat([english_diff_minor, french_diff_minor, spanish_diff_minor, greek_diff_minor, croatian_diff_minor],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_french_minor.columns, new_column_names)}
diff_finetune_french_minor = diff_finetune_french_minor.rename(columns=column_mapping).transpose()

In [42]:
diff_finetune_french

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-0.074886,0.007384,-0.042112,-0.063423,-0.020434,-0.087577,0.043194,-0.033120,-0.030034,0.035077
French,-0.019161,-0.002253,0.002528,-0.008684,-0.044385,-0.035646,0.019154,0.001454,-0.030995,0.002790
Spanish,-0.009725,0.000977,0.002811,-0.001739,-0.054137,-0.001902,-0.020103,0.006816,-0.026309,-0.012560
Greek,-0.004835,0.027518,0.028549,-0.000739,0.012846,0.023232,0.020383,0.044440,0.033758,0.016244
Croatian,-0.008146,0.042540,-0.009073,-0.017223,-0.007740,-0.011602,0.003104,0.022075,0.011820,0.065531

In [43]:
diff_finetune_french_perc = (diff_finetune_french/df_pretrain)*100

In [44]:
diff_finetune_french_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-81.843270,13.998207,-59.443878,-51.403846,-32.297440,-45.691118,24.649702,-40.068908,-80.445978,31.499559
French,-29.109360,-3.723190,5.159365,-9.851654,-56.832308,-22.656657,8.055749,2.281463,-62.605277,1.859390
Spanish,-16.962756,1.697101,5.770087,-2.124704,-62.376492,-1.497540,-7.368807,11.571958,-58.104382,-7.671450
Greek,-7.424696,22.608717,290.087729,-1.290414,16.484670,19.293288,6.961956,129.990221,86.162072,8.947484
Croatian,-10.807800,62.349924,-16.870984,-20.069909,-10.367939,-7.306239,1.286387,40.868926,40.280477,41.292409

In [45]:
diff_finetune_french_perc_race = (diff_finetune_french_race/df_pretrain)*100

In [46]:
diff_finetune_french_perc_race

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-85.025405,24.815340,-66.712988,-58.289759,-45.714532,-44.798563,33.287858,-47.014861,-85.597217,46.842173
French,-35.700106,2.258499,0.378448,-21.276511,-71.255722,-30.380684,7.555710,-8.733836,-70.807181,5.408501
Spanish,-25.704513,6.880178,-2.191109,-10.809900,-68.880367,-5.417595,-10.747027,15.474625,-67.019325,-5.258591
Greek,-24.521739,17.021201,279.403922,6.974952,5.426443,10.660856,0.402571,149.197824,94.844117,-1.141207
Croatian,-15.421372,63.945343,-44.872676,-31.505009,-11.988519,-16.078652,3.037700,47.886353,69.703493,38.773258

In [47]:
diff_finetune_french_perc_minor = (diff_finetune_french_minor/df_pretrain_minor)*100

In [48]:
diff_finetune_french_perc_minor

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-95.778438,35.726129,-78.670880,-69.826876,-34.390474,-60.364680,44.260345,-60.008356,-90.348795,58.275110
French,-42.330345,2.668257,-11.256061,-25.955367,-60.347617,-34.680574,19.954694,-19.168965,-70.419884,20.981995
Spanish,-38.185102,8.672278,-13.336588,-22.048672,-67.299558,-14.958066,-9.226646,-0.208056,-67.853492,-4.972643
Greek,-9.914564,11.667119,231.900099,10.651290,-3.614734,26.177591,0.567143,179.077478,77.790164,1.456975
Croatian,-21.340123,87.197562,-38.008742,-33.029902,-7.764478,-15.668054,5.457197,31.539378,82.295606,45.576906

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_french_perc.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_french_perc.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_french = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_french

           English    French   Spanish     Greek  Croatian
English   1.000000  0.705783  0.494710 -0.550649  0.057304
French    0.705783  1.000000  0.931838 -0.153735 -0.150331
Spanish   0.494710  0.931838  1.000000 -0.096706 -0.148066
Greek    -0.550649 -0.153735 -0.096706  1.000000  0.166347
Croatian  0.057304 -0.150331 -0.148066  0.166347  1.000000

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_french_perc_race.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_french_perc_race.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_french_race = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_french_race

           English    French   Spanish     Greek  Croatian
English   1.000000  0.774776  0.591078 -0.540439  0.116544
French    0.774776  1.000000  0.923101 -0.208230 -0.167014
Spanish   0.591078  0.923101  1.000000 -0.129885 -0.150962
Greek    -0.540439 -0.208230 -0.129885  1.000000  0.051356
Croatian  0.116544 -0.167014 -0.150962  0.051356  1.000000

In [51]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_french_perc_minor.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_french_perc_minor.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_french_minor = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_french_minor

           English    French   Spanish     Greek  Croatian
English   1.000000  0.848495  0.675906 -0.578087  0.174327
French    0.848495  1.000000  0.907671 -0.337252 -0.113092
Spanish   0.675906  0.907671  1.000000 -0.252812 -0.148037
Greek    -0.578087 -0.337252 -0.252812  1.000000  0.086479
Croatian  0.174327 -0.113092 -0.148037  0.086479  1.000000

In [52]:
row_index1 = 0
row_index2 = 1
row_index3 = 2
row_index4 = 3

# Get the rows as NumPy arrays
row1 = diff_finetune_french_perc.iloc[row_index1].values.reshape(1, -1)
row2 = diff_finetune_french_perc.iloc[row_index2].values.reshape(1, -1)
row3 = diff_finetune_french_perc.iloc[row_index3].values.reshape(1, -1)
row4 = diff_finetune_french_perc.iloc[row_index4].values.reshape(1, -1)

# Calculate the cosine similarity between the two rows
similarity = cosine_similarity(row1, row2)[0, 0]
similarity2 = cosine_similarity(row1, row3)[0, 0]
print("Similarity between english and french is:  ", similarity)
print("Similarity between english and spanish is:  ", similarity2)

Similarity between english and french is:   0.7057829573505741
Similarity between english and spanish is:   0.4947097032324757

## Greek Finetuning

In [53]:
## For Greek finetuning

english_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/greek_finetune/emotion_profiles/english/"
french_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/greek_finetune/emotion_profiles/french/"
spanish_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/greek_finetune/emotion_profiles/spanish/"
greek_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/greek_finetune/emotion_profiles/greek/"
croatian_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/greek_finetune/emotion_profiles/croatian/"



english_finetune = find_emotions(english_path)
french_finetune = find_emotions(french_path)
spanish_finetune = find_emotions(spanish_path)
greek_finetune = find_emotions(greek_path)
croatian_finetune = find_emotions(croatian_path)

english_finetune = english_finetune.div(english_finetune.sum())
french_finetune = french_finetune.div(french_finetune.sum())
spanish_finetune = spanish_finetune.div(spanish_finetune.sum())
greek_finetune = greek_finetune.div(greek_finetune.sum())
croatian_finetune = croatian_finetune.div(croatian_finetune.sum())

In [54]:
# to obtain race

english_finetune_race = find_race(english_path)
french_finetune_race = find_race(french_path)
spanish_finetune_race = find_race(spanish_path)
greek_finetune_race = find_race(greek_path)
croatian_finetune_race = find_race(croatian_path)

english_finetune_race = english_finetune_race.div(english_finetune_race.sum())
french_finetune_race = french_finetune_race.div(french_finetune_race.sum())
spanish_finetune_race = spanish_finetune_race.div(spanish_finetune_race.sum())
greek_finetune_race = greek_finetune_race.div(greek_finetune_race.sum())
croatian_finetune_race = croatian_finetune_race.div(croatian_finetune_race.sum())

In [55]:
# to obtain racial minorities 

english_finetune_minor = find_minor(english_path)
french_finetune_minor = find_minor(french_path)
spanish_finetune_minor = find_minor(spanish_path)
greek_finetune_minor = find_minor(greek_path)
croatian_finetune_minor = find_minor(croatian_path)

english_finetune_minor = english_finetune_minor.div(english_finetune_minor.sum())
french_finetune_minor = french_finetune_minor.div(french_finetune_minor.sum())
spanish_finetune_minor = spanish_finetune_minor.div(spanish_finetune_minor.sum())
greek_finetune_minor = greek_finetune_minor.div(greek_finetune_minor.sum())
croatian_finetune_minor = croatian_finetune_minor.div(croatian_finetune_minor.sum())

In [56]:

english_diff = english_finetune - english_pretrain
french_diff = spanish_finetune-french_pretrain
spanish_diff = spanish_finetune-spanish_pretrain
greek_diff = greek_finetune-greek_pretrain
croatian_diff =  croatian_finetune- croatian_pretrain

In [57]:
# race diff

english_diff_race = english_finetune_race - english_pretrain_race
french_diff_race = spanish_finetune_race-french_pretrain_race
spanish_diff_race = spanish_finetune_race-spanish_pretrain_race
greek_diff_race = greek_finetune_race-greek_pretrain_race
croatian_diff_race =  croatian_finetune_race- croatian_pretrain_race

In [58]:
# minor diff

english_diff_minor = english_finetune_minor - english_pretrain_minor
french_diff_minor = spanish_finetune_minor-french_pretrain_minor
spanish_diff_minor = spanish_finetune_minor-spanish_pretrain_minor
greek_diff_minor = greek_finetune_minor-greek_pretrain_minor
croatian_diff_minor =  croatian_finetune_minor- croatian_pretrain_minor

In [59]:
diff_finetune_greek = pd.concat([english_diff, french_diff, spanish_diff, greek_diff, croatian_diff],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_greek.columns, new_column_names)}
diff_finetune_greek = diff_finetune_greek.rename(columns=column_mapping).transpose()

In [60]:
# for race

diff_finetune_greek_race = pd.concat([english_diff_race, french_diff_race, spanish_diff_race, greek_diff_race, croatian_diff_race],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_greek_race.columns, new_column_names)}
diff_finetune_greek_race = diff_finetune_greek_race.rename(columns=column_mapping).transpose()

In [61]:
# for minor

diff_finetune_greek_minor = pd.concat([english_diff_minor, french_diff_minor, spanish_diff_minor, greek_diff_minor, croatian_diff_minor],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_greek_minor.columns, new_column_names)}
diff_finetune_greek_minor = diff_finetune_greek_minor.rename(columns=column_mapping).transpose()

In [62]:
diff_finetune_greek

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-0.064846,-0.012856,-0.030780,-0.074567,-0.012815,-0.037973,0.022864,-0.026904,-0.027272,-0.000782
French,-0.023569,0.013241,-0.027743,-0.010755,-0.032432,-0.050021,0.042302,0.008890,-0.035340,0.000229
Spanish,-0.014132,0.016471,-0.027460,-0.003810,-0.042184,-0.016276,0.003045,0.014252,-0.030655,-0.015121
Greek,-0.010412,0.078283,0.043236,-0.006969,0.013060,0.021940,0.011840,0.041410,0.027708,-0.018700
Croatian,-0.018530,0.039365,-0.011107,-0.032701,0.005544,-0.030834,0.027015,0.007776,0.015394,0.089364

In [63]:
diff_finetune_greek_perc = (diff_finetune_greek/df_pretrain)*100

In [64]:
diff_finetune_greek_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-70.870349,-24.370288,-43.447732,-60.436054,-20.254616,-19.811254,13.047624,-32.548722,-73.047634,-0.702487
French,-35.805806,21.882370,-56.609669,-12.201258,-41.527392,-31.792807,17.791236,13.945476,-71.382467,0.152878
Spanish,-24.651670,28.606157,-56.357878,-4.654437,-48.604352,-12.816011,1.116335,24.195094,-67.701285,-9.235522
Greek,-15.988374,64.318043,439.322261,-12.164546,16.759517,18.220356,4.044015,121.126040,70.719318,-10.300146
Croatian,-24.586461,57.696199,-20.653789,-38.106959,7.426957,-19.417852,11.195219,14.396509,52.461153,56.310311

In [65]:
diff_finetune_greek_perc_race = (diff_finetune_greek_race/df_pretrain_race)*100

In [66]:
diff_finetune_greek_perc_race

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-70.746490,-24.724270,-45.357149,-63.843142,-29.588884,-16.622510,22.261873,-38.839213,-70.631136,15.961060
French,-41.547812,33.456834,-59.215830,-23.624945,-51.520216,-37.691978,19.718586,1.657749,-77.115345,1.160171
Spanish,-31.711999,39.350840,-59.770821,-14.233041,-53.504550,-15.674082,-0.941771,28.104113,-72.998729,-9.722326
Greek,-28.295116,63.853153,379.662910,-5.876037,4.118843,9.598992,-0.516369,174.838531,74.725363,-20.124936
Croatian,-28.670390,60.259071,-34.642350,-46.614942,7.052402,-25.639277,12.742536,24.051886,104.076224,53.191506

In [67]:
diff_finetune_greek_perc_minor = (diff_finetune_greek_minor/df_pretrain_minor)*100

In [68]:
diff_finetune_greek_perc_minor

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-88.035572,-17.990079,-61.841736,-77.071331,-24.536767,-35.452781,29.448534,-52.732765,-79.968664,19.834524
French,-48.841864,34.391191,-67.250350,-29.494379,-45.940719,-44.147358,32.702950,-9.820515,-76.573760,19.086005
Spanish,-45.362075,42.901830,-70.004836,-25.873818,-53.836791,-27.124727,1.089706,11.303465,-74.812496,-6.554484
Greek,-17.582080,54.380903,340.596366,-2.736148,-2.932729,24.971051,-0.718654,161.000064,53.544389,-17.786720
Croatian,-36.357547,81.126624,-40.382599,-51.574094,11.126851,-27.868552,19.044415,5.367588,96.285509,64.476527

In [69]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_greek_perc.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_greek_perc.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_greek = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_greek

           English    French   Spanish     Greek  Croatian
English   1.000000  0.738797  0.606671 -0.449075 -0.027811
French    0.738797  1.000000  0.957420 -0.504204  0.057806
Spanish   0.606671  0.957420  1.000000 -0.486051 -0.018077
Greek    -0.449075 -0.504204 -0.486051  1.000000  0.003518
Croatian -0.027811  0.057806 -0.018077  0.003518  1.000000

In [70]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_greek_perc_race.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_greek_perc_race.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_greek_race = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_greek_race

           English    French   Spanish     Greek  Croatian
English   1.000000  0.765220  0.598150 -0.475781 -0.086021
French    0.765220  1.000000  0.941463 -0.442694 -0.035621
Spanish   0.598150  0.941463  1.000000 -0.369374 -0.074502
Greek    -0.475781 -0.442694 -0.369374  1.000000  0.037825
Croatian -0.086021 -0.035621 -0.074502  0.037825  1.000000

In [71]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_greek_perc_minor.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_greek_perc_minor.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_greek_minor = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_greek_minor

           English    French   Spanish     Greek  Croatian
English   1.000000  0.838172  0.717766 -0.510991  0.097805
French    0.838172  1.000000  0.935468 -0.491479  0.168499
Spanish   0.717766  0.935468  1.000000 -0.438086  0.084461
Greek    -0.510991 -0.491479 -0.438086  1.000000 -0.069973
Croatian  0.097805  0.168499  0.084461 -0.069973  1.000000

In [72]:
row_index1 = 0
row_index2 = 1
row_index3 = 2
row_index4 = 3

# Get the rows as NumPy arrays
row1 = diff_finetune_greek_perc.iloc[row_index1].values.reshape(1, -1)
row2 = diff_finetune_greek_perc.iloc[row_index2].values.reshape(1, -1)
row3 = diff_finetune_greek_perc.iloc[row_index3].values.reshape(1, -1)
row4 = diff_finetune_greek_perc.iloc[row_index4].values.reshape(1, -1)

# Calculate the cosine similarity between the two rows
similarity = cosine_similarity(row1, row2)[0, 0]
similarity2 = cosine_similarity(row1, row3)[0, 0]
print("Similarity between english and french is:  ", similarity)
print("Similarity between english and spanish is:  ", similarity2)

Similarity between english and french is:   0.7387965716207786
Similarity between english and spanish is:   0.606671202338848

## Spanish finetune

In [73]:
## For Spanish finetuning

english_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/spanish_finetune/emotion_profiles/english/"
french_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/spanish_finetune/emotion_profiles/french/"
spanish_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/spanish_finetune/emotion_profiles/spanish/"
greek_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/spanish_finetune/emotion_profiles/greek/"
croatian_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/spanish_finetune/emotion_profiles/croatian/"



english_finetune = find_emotions(english_path)
french_finetune = find_emotions(french_path)
spanish_finetune = find_emotions(spanish_path)
greek_finetune = find_emotions(greek_path)
croatian_finetune = find_emotions(croatian_path)

english_finetune = english_finetune.div(english_finetune.sum())
french_finetune = french_finetune.div(french_finetune.sum())
spanish_finetune = spanish_finetune.div(spanish_finetune.sum())
greek_finetune = greek_finetune.div(greek_finetune.sum())
croatian_finetune = croatian_finetune.div(croatian_finetune.sum())

In [74]:
# to obtain race

english_finetune_race = find_race(english_path)
french_finetune_race = find_race(french_path)
spanish_finetune_race = find_race(spanish_path)
greek_finetune_race = find_race(greek_path)
croatian_finetune_race = find_race(croatian_path)

english_finetune_race = english_finetune_race.div(english_finetune_race.sum())
french_finetune_race = french_finetune_race.div(french_finetune_race.sum())
spanish_finetune_race = spanish_finetune_race.div(spanish_finetune_race.sum())
greek_finetune_race = greek_finetune_race.div(greek_finetune_race.sum())
croatian_finetune_race = croatian_finetune_race.div(croatian_finetune_race.sum())

In [75]:
# to obtain racial minorities 

english_finetune_minor = find_minor(english_path)
french_finetune_minor = find_minor(french_path)
spanish_finetune_minor = find_minor(spanish_path)
greek_finetune_minor = find_minor(greek_path)
croatian_finetune_minor = find_minor(croatian_path)

english_finetune_minor = english_finetune_minor.div(english_finetune_minor.sum())
french_finetune_minor = french_finetune_minor.div(french_finetune_minor.sum())
spanish_finetune_minor = spanish_finetune_minor.div(spanish_finetune_minor.sum())
greek_finetune_minor = greek_finetune_minor.div(greek_finetune_minor.sum())
croatian_finetune_minor = croatian_finetune_minor.div(croatian_finetune_minor.sum())

In [76]:
english_diff = english_finetune - english_pretrain
french_diff = spanish_finetune-french_pretrain
spanish_diff = spanish_finetune-spanish_pretrain
greek_diff = greek_finetune-greek_pretrain
croatian_diff =  croatian_finetune- croatian_pretrain

In [77]:
# race diff

english_diff_race = english_finetune_race - english_pretrain_race
french_diff_race = spanish_finetune_race-french_pretrain_race
spanish_diff_race = spanish_finetune_race-spanish_pretrain_race
greek_diff_race = greek_finetune_race-greek_pretrain_race
croatian_diff_race =  croatian_finetune_race- croatian_pretrain_race

In [78]:
# minor diff

english_diff_minor = english_finetune_minor - english_pretrain_minor
french_diff_minor = spanish_finetune_minor-french_pretrain_minor
spanish_diff_minor = spanish_finetune_minor-spanish_pretrain_minor
greek_diff_minor = greek_finetune_minor-greek_pretrain_minor
croatian_diff_minor =  croatian_finetune_minor- croatian_pretrain_minor

In [79]:
diff_finetune_spanish = pd.concat([english_diff, french_diff, spanish_diff, greek_diff, croatian_diff],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_spanish.columns, new_column_names)}
diff_finetune_spanish = diff_finetune_spanish.rename(columns=column_mapping).transpose()

In [80]:
# for race

diff_finetune_spanish_race = pd.concat([english_diff_race, french_diff_race, spanish_diff_race, greek_diff_race, croatian_diff_race],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_spanish_race.columns, new_column_names)}
diff_finetune_spanish_race = diff_finetune_spanish_race.rename(columns=column_mapping).transpose()

In [81]:
# for minor

diff_finetune_spanish_minor = pd.concat([english_diff_minor, french_diff_minor, spanish_diff_minor, greek_diff_minor, croatian_diff_minor],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_spanish_minor.columns, new_column_names)}
diff_finetune_spanish_minor = diff_finetune_spanish_minor.rename(columns=column_mapping).transpose()

In [82]:
diff_finetune_spanish

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-0.058957,-0.006809,-0.049953,-0.053859,-0.032468,-0.057876,0.035161,-0.028937,-0.023880,0.011648
French,-0.028614,0.009237,-0.004689,-0.029422,-0.048120,-0.084554,0.060156,-0.006259,-0.029838,0.046907
Spanish,-0.019177,0.012467,-0.004406,-0.022478,-0.057872,-0.050809,0.020900,-0.000897,-0.025153,0.031557
Greek,-0.019268,0.053976,0.002962,-0.007461,0.019986,0.002941,0.046534,0.029272,0.038443,0.034010
Croatian,0.006578,0.021060,0.002957,-0.022351,-0.013549,-0.008295,0.019691,-0.001623,0.007836,0.078983

In [83]:
diff_finetune_spanish_perc = (diff_finetune_spanish/df_pretrain)*100

In [84]:
diff_finetune_spanish_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-64.433748,-12.908294,-70.511006,-43.652430,-51.318327,-30.195228,20.065425,-35.008769,-63.963989,10.459632
French,-43.469784,15.264669,-9.568286,-33.380514,-61.614917,-53.741964,25.300341,-9.818444,-60.269945,31.259175
Spanish,-33.451512,21.651571,-9.043145,-27.457371,-66.680127,-40.008085,7.661033,-1.522914,-55.550951,19.274386
Greek,-29.587237,44.347028,30.096522,-13.023127,25.648263,2.442065,15.893924,85.623541,98.118770,18.733158
Croatian,8.727675,30.866502,5.498294,-26.046606,-18.149393,-5.224145,8.160039,-3.004065,26.703928,49.769398

In [85]:
diff_finetune_spanish_perc_race = (diff_finetune_spanish_race/df_pretrain)*100

In [86]:
diff_finetune_spanish_perc_race

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-65.752506,-17.626797,-74.326163,-48.684384,-58.782449,-26.480747,27.925083,-43.457733,-63.635931,19.643529
French,-52.687791,22.538896,-7.752164,-45.698125,-77.656400,-55.918886,24.044699,-22.180127,-66.605332,29.989001
Spanish,-45.209913,28.192984,-10.368966,-37.103761,-74.640022,-37.056017,3.624254,0.922657,-62.425060,17.270217
Greek,-30.967444,36.425219,6.896209,-9.508716,4.922966,3.007272,10.631001,100.336447,64.573762,12.666913
Croatian,4.458366,31.080202,-20.222091,-37.264360,-21.410053,-13.189009,9.121217,-2.356396,54.551565,50.414360

In [87]:
diff_finetune_spanish_perc_minor = (diff_finetune_spanish_minor/df_pretrain)*100

In [88]:
diff_finetune_spanish_perc_minor

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-91.460397,-14.240285,-93.844407,-69.268891,-53.385480,-45.847393,28.946457,-61.364012,-64.495255,19.641635
French,-65.691967,20.327150,-30.821779,-51.800936,-66.463778,-66.538230,35.387328,-30.778205,-66.668278,40.967810
Spanish,-65.488257,26.502605,-33.242109,-48.848795,-70.421077,-50.654144,7.160003,-8.419541,-61.035897,17.295611
Greek,-25.100067,33.038850,-12.685562,-2.750202,3.417375,6.791327,11.380819,92.135165,77.446413,14.334963
Croatian,-0.371318,36.903328,-19.636613,-39.772369,-21.549422,-13.881828,9.239104,-10.685881,49.429197,51.511095

In [89]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_spanish_perc.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_spanish_perc.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_spanish = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_spanish

           English    French   Spanish     Greek  Croatian
English   1.000000  0.818800  0.783505 -0.485816 -0.003901
French    0.818800  1.000000  0.973169 -0.291093  0.274421
Spanish   0.783505  0.973169  1.000000 -0.298941  0.249988
Greek    -0.485816 -0.291093 -0.298941  1.000000  0.418747
Croatian -0.003901  0.274421  0.249988  0.418747  1.000000

In [90]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_spanish_perc_race.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_spanish_perc_race.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_spanish_race = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_spanish_race

           English    French   Spanish     Greek  Croatian
English   1.000000  0.822266  0.771035 -0.345850  0.133789
French    0.822266  1.000000  0.965509 -0.191144  0.208926
Spanish   0.771035  0.965509  1.000000 -0.089588  0.156558
Greek    -0.345850 -0.191144 -0.089588  1.000000  0.411035
Croatian  0.133789  0.208926  0.156558  0.411035  1.000000

In [91]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_spanish_perc_minor.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_spanish_perc_minor.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_spanish_minor = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_spanish_minor

           English    French   Spanish     Greek  Croatian
English   1.000000  0.881199  0.857954 -0.297010  0.252867
French    0.881199  1.000000  0.958291 -0.233631  0.342124
Spanish   0.857954  0.958291  1.000000 -0.145918  0.281385
Greek    -0.297010 -0.233631 -0.145918  1.000000  0.409263
Croatian  0.252867  0.342124  0.281385  0.409263  1.000000

In [92]:
row_index1 = 0
row_index2 = 1
row_index3 = 2
row_index4 = 3

# Get the rows as NumPy arrays
row1 = diff_finetune_spanish_perc.iloc[row_index1].values.reshape(1, -1)
row2 = diff_finetune_spanish_perc.iloc[row_index2].values.reshape(1, -1)
row3 = diff_finetune_spanish_perc.iloc[row_index3].values.reshape(1, -1)
row4 = diff_finetune_spanish_perc.iloc[row_index4].values.reshape(1, -1)

# Calculate the cosine similarity between the two rows
similarity = cosine_similarity(row1, row2)[0, 0]
similarity2 = cosine_similarity(row1, row3)[0, 0]
print("Similarity between english and french is:  ", similarity)
print("Similarity between english and spanish is:  ", similarity2)

Similarity between english and french is:   0.8187996558762922
Similarity between english and spanish is:   0.7835048327172243

## Analysis

### English Finetuning

In [93]:
diff_finetune_english_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-13.932827,-33.244216,-2.707444,-18.034139,-89.437734,-12.535124,-41.859546,-29.333757,-20.230978,-16.869612
French,0.050706,25.595529,-7.509493,-14.952889,-58.303910,-11.772766,-16.815704,-42.451557,-23.401975,-9.773513
Spanish,15.344862,31.405221,-10.124885,-4.001486,-57.225670,17.635131,-31.988379,-21.015677,-15.186888,-19.173389
Greek,35.360173,-43.072753,759.965796,114.276148,2.542128,136.496226,-38.117898,127.273878,90.443185,-57.268153
Croatian,34.511315,43.797474,-34.530368,-9.510251,-9.799216,14.295108,-4.366489,63.261226,58.918240,-15.077597

In [94]:
diff_finetune_english_perc.mean()

anger            14.266846
anticipation      4.896251
disgust         141.018721
fear             13.555477
joy             -42.444880
negative         28.823715
positive        -26.629603
sadness          19.546822
surprise         18.108317
trust           -23.632453
dtype: float64

In [95]:
diff_finetune_english_perc.loc[diff_finetune_english_perc.index != 'Greek'].mean()

anger            8.993514
anticipation    16.888502
disgust        -13.718048
fear           -11.624691
joy            -53.691632
negative         1.905587
positive       -23.757529
sadness         -7.384941
surprise         0.024600
trust          -15.223528
dtype: float64

In [96]:
similarity_df_english

           English    French   Spanish     Greek  Croatian
English   1.000000  0.760816  0.661147 -0.088587 -0.281214
French    0.760816  1.000000  0.851686 -0.244102 -0.202686
Spanish   0.661147  0.851686  1.000000 -0.125919  0.140656
Greek    -0.088587 -0.244102 -0.125919  1.000000 -0.130656
Croatian -0.281214 -0.202686  0.140656 -0.130656  1.000000

### French Finetuning

In [97]:
diff_finetune_french_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-81.843270,13.998207,-59.443878,-51.403846,-32.297440,-45.691118,24.649702,-40.068908,-80.445978,31.499559
French,-29.109360,-3.723190,5.159365,-9.851654,-56.832308,-22.656657,8.055749,2.281463,-62.605277,1.859390
Spanish,-16.962756,1.697101,5.770087,-2.124704,-62.376492,-1.497540,-7.368807,11.571958,-58.104382,-7.671450
Greek,-7.424696,22.608717,290.087729,-1.290414,16.484670,19.293288,6.961956,129.990221,86.162072,8.947484
Croatian,-10.807800,62.349924,-16.870984,-20.069909,-10.367939,-7.306239,1.286387,40.868926,40.280477,41.292409

In [98]:
diff_finetune_french_perc.mean()

anger          -29.229577
anticipation    19.386152
disgust         44.940464
fear           -16.948105
joy            -29.077902
negative       -11.571653
positive         6.716998
sadness         28.928732
surprise       -14.942618
trust           15.185478
dtype: float64

In [99]:
diff_finetune_french_perc.loc[diff_finetune_french_perc.index != 'Greek'].mean()

anger          -34.680797
anticipation    18.580511
disgust        -16.346352
fear           -20.862528
joy            -40.468545
negative       -19.287888
positive         6.655758
sadness          3.663360
surprise       -40.218790
trust           16.744977
dtype: float64

In [100]:
similarity_df_french

           English    French   Spanish     Greek  Croatian
English   1.000000  0.705783  0.494710 -0.550649  0.057304
French    0.705783  1.000000  0.931838 -0.153735 -0.150331
Spanish   0.494710  0.931838  1.000000 -0.096706 -0.148066
Greek    -0.550649 -0.153735 -0.096706  1.000000  0.166347
Croatian  0.057304 -0.150331 -0.148066  0.166347  1.000000

### Spanish Finetune

In [101]:
diff_finetune_spanish_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-64.433748,-12.908294,-70.511006,-43.652430,-51.318327,-30.195228,20.065425,-35.008769,-63.963989,10.459632
French,-43.469784,15.264669,-9.568286,-33.380514,-61.614917,-53.741964,25.300341,-9.818444,-60.269945,31.259175
Spanish,-33.451512,21.651571,-9.043145,-27.457371,-66.680127,-40.008085,7.661033,-1.522914,-55.550951,19.274386
Greek,-29.587237,44.347028,30.096522,-13.023127,25.648263,2.442065,15.893924,85.623541,98.118770,18.733158
Croatian,8.727675,30.866502,5.498294,-26.046606,-18.149393,-5.224145,8.160039,-3.004065,26.703928,49.769398

In [102]:
diff_finetune_spanish_perc.mean()

anger          -32.442921
anticipation    19.844295
disgust        -10.705524
fear           -28.712010
joy            -34.422900
negative       -25.345471
positive        15.416152
sadness          7.253870
surprise       -10.992437
trust           25.899150
dtype: float64

In [103]:
diff_finetune_spanish_perc.loc[diff_finetune_spanish_perc.index != 'Greek'].mean()

anger          -33.156842
anticipation    13.718612
disgust        -20.906036
fear           -32.634230
joy            -49.440691
negative       -32.292355
positive        15.296709
sadness        -12.338548
surprise       -38.270239
trust           27.690648
dtype: float64

In [104]:
similarity_df_spanish

           English    French   Spanish     Greek  Croatian
English   1.000000  0.818800  0.783505 -0.485816 -0.003901
French    0.818800  1.000000  0.973169 -0.291093  0.274421
Spanish   0.783505  0.973169  1.000000 -0.298941  0.249988
Greek    -0.485816 -0.291093 -0.298941  1.000000  0.418747
Croatian -0.003901  0.274421  0.249988  0.418747  1.000000

### Greek Finetune

In [105]:
diff_finetune_greek_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-70.870349,-24.370288,-43.447732,-60.436054,-20.254616,-19.811254,13.047624,-32.548722,-73.047634,-0.702487
French,-35.805806,21.882370,-56.609669,-12.201258,-41.527392,-31.792807,17.791236,13.945476,-71.382467,0.152878
Spanish,-24.651670,28.606157,-56.357878,-4.654437,-48.604352,-12.816011,1.116335,24.195094,-67.701285,-9.235522
Greek,-15.988374,64.318043,439.322261,-12.164546,16.759517,18.220356,4.044015,121.126040,70.719318,-10.300146
Croatian,-24.586461,57.696199,-20.653789,-38.106959,7.426957,-19.417852,11.195219,14.396509,52.461153,56.310311

In [106]:
diff_finetune_greek_perc.mean()

anger          -34.380532
anticipation    29.626496
disgust         52.450638
fear           -25.512651
joy            -17.239977
negative       -13.123514
positive         9.438886
sadness         28.222879
surprise       -17.790183
trust            7.245007
dtype: float64

In [107]:
diff_finetune_greek_perc.loc[diff_finetune_greek_perc.index != 'Greek'].mean()

anger          -38.978572
anticipation    20.953610
disgust        -44.267267
fear           -28.849677
joy            -25.739851
negative       -20.959481
positive        10.787604
sadness          4.997089
surprise       -39.917558
trust           11.631295
dtype: float64

In [108]:
similarity_df_greek

           English    French   Spanish     Greek  Croatian
English   1.000000  0.738797  0.606671 -0.449075 -0.027811
French    0.738797  1.000000  0.957420 -0.504204  0.057806
Spanish   0.606671  0.957420  1.000000 -0.486051 -0.018077
Greek    -0.449075 -0.504204 -0.486051  1.000000  0.003518
Croatian -0.027811  0.057806 -0.018077  0.003518  1.000000