In [1]:
import pandas as pd
import os
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
!pwd

/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out

In [3]:
def find_emotions(folder_path):

#     folder_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/english/"
    # english_pretrain = pd.read_csv(file_path)

    dataframes = []

    # Iterate over all files in the folder
    for filename in os.listdir(folder_path):
        # Check if the file is a CSV file
        if filename.endswith(".csv"):
            # Construct the file path
            file_path = os.path.join(folder_path, filename)
            # Load the CSV file into a DataFrame
            df = pd.read_csv(file_path)
            # Append the DataFrame to the list
            dataframes.append(df)

    # Concatenate all DataFrames into one
    combined_df = pd.concat(dataframes, ignore_index=True)

    # Now you can work with the combined DataFrame
    combined_df.rename( columns={'Unnamed: 0':'group'}, inplace=True )
    combined_df = combined_df.iloc[:, 1:]
    return combined_df.mean(0)

In [5]:
def find_race(folder_path):
    file_path = os.path.join(folder_path, "race.csv")
    df = pd.read_csv(file_path)
    df.rename(columns={'Unnamed: 0':'group'}, inplace=True)
    df = df.iloc[:, 1:]
    return df.mean(0)

In [6]:
english_pretrain_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/english/"
french_pretrain_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/french/"
spanish_pretrain_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/spanish/"
greek_pretrain_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/greek/"
croatian_pretrain_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/pretrained_roberta/emotion_profiles/croatian/"



english_pretrain = find_emotions(english_pretrain_path)
french_pretrain = find_emotions(french_pretrain_path)
spanish_pretrain = find_emotions(spanish_pretrain_path)
greek_pretrain = find_emotions(greek_pretrain_path)
croatian_pretrain = find_emotions(croatian_pretrain_path)

In [7]:
# to obtain race

english_pretrain_race = find_race(english_pretrain_path)
french_pretrain_race = find_race(french_pretrain_path)
spanish_pretrain_race = find_race(spanish_pretrain_path)
greek_pretrain_race = find_race(greek_pretrain_path)
croatian_pretrain_race = find_race(croatian_pretrain_path)

In [8]:
df_pretrain = pd.concat([english_pretrain, french_pretrain, spanish_pretrain, greek_pretrain, croatian_pretrain],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(df_pretrain.columns, new_column_names)}
df_pretrain = df_pretrain.rename(columns=column_mapping).transpose()
df_pretrain = df_pretrain.div(df_pretrain.sum(axis=1), axis=0)

In [9]:
df_pretrain

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,0.089924,0.053622,0.069939,0.121567,0.063528,0.190526,0.178182,0.081669,0.037432,0.113609
French,0.065105,0.060976,0.048330,0.086942,0.078027,0.155791,0.240516,0.062585,0.049331,0.152396
Spanish,0.056240,0.058290,0.047911,0.080495,0.087046,0.125981,0.274799,0.058491,0.045246,0.165501
Greek,0.065247,0.121421,0.009619,0.058210,0.076508,0.121570,0.292551,0.034738,0.039073,0.181062
Croatian,0.074524,0.069163,0.052159,0.084396,0.075013,0.157425,0.243877,0.053601,0.029937,0.159905

In [10]:
# for race

df_pretrain_race = pd.concat([english_pretrain_race, french_pretrain_race, spanish_pretrain_race, greek_pretrain_race, croatian_pretrain_race],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(df_pretrain_race.columns, new_column_names)}
df_pretrain_race = df_pretrain_race.rename(columns=column_mapping).transpose()
df_pretrain_race = df_pretrain_race.div(df_pretrain_race.sum(axis=1), axis=0)

## For English Finetuning

In [11]:
## For English finetuning

english_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/finetuned_stereoset_english/emotion_profiles/english/"
french_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/finetuned_stereoset_english/emotion_profiles/french/"
spanish_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/finetuned_stereoset_english/emotion_profiles/spanish/"
greek_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/finetuned_stereoset_english/emotion_profiles/greek/"
croatian_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/finetuned_stereoset_english/emotion_profiles/croatian/"



english_finetune = find_emotions(english_path)
french_finetune = find_emotions(french_path)
spanish_finetune = find_emotions(spanish_path)
greek_finetune = find_emotions(greek_path)
croatian_finetune = find_emotions(croatian_path)

english_finetune = english_finetune.div(english_finetune.sum())
french_finetune = french_finetune.div(french_finetune.sum())
spanish_finetune = spanish_finetune.div(spanish_finetune.sum())
greek_finetune = greek_finetune.div(greek_finetune.sum())
croatian_finetune = croatian_finetune.div(croatian_finetune.sum())

In [12]:
# to obtain race

english_finetune_race = find_race(english_pretrain_path)
french_finetune_race = find_race(french_pretrain_path)
spanish_finetune_race = find_race(spanish_pretrain_path)
greek_finetune_race = find_race(greek_pretrain_path)
croatian_finetune_race = find_race(croatian_pretrain_path)


english_finetune_race = english_finetune_race.div(english_finetune_race.sum())
french_finetune_race = french_finetune_race.div(french_finetune_race.sum())
spanish_finetune_race = spanish_finetune_race.div(spanish_finetune_race.sum())
greek_finetune_race = greek_finetune_race.div(greek_finetune_race.sum())
croatian_finetune_race = croatian_finetune_race.div(croatian_finetune_race.sum())

In [13]:
english_diff = english_finetune - english_pretrain_race
french_diff = spanish_finetune-french_pretrain_race
spanish_diff = spanish_finetune-spanish_pretrain_race
greek_diff = greek_finetune-greek_pretrain_race
croatian_diff =  croatian_finetune- croatian_pretrain_race

In [14]:
# race diff

english_diff_race = english_finetune_race - english_pretrain_race
french_diff_race = spanish_finetune_race-french_pretrain_race
spanish_diff_race = spanish_finetune_race-spanish_pretrain_race
greek_diff_race = greek_finetune_race-greek_pretrain_race
croatian_diff_race =  croatian_finetune_race- croatian_pretrain_race

In [15]:
diff_finetune_english = pd.concat([english_diff, french_diff, spanish_diff, greek_diff, croatian_diff],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_english.columns, new_column_names)}
diff_finetune_english = diff_finetune_english.rename(columns=column_mapping).transpose()

In [16]:
# for race

diff_finetune_english_race = pd.concat([english_diff_race, french_diff_race, spanish_diff_race, greek_diff_race, croatian_diff_race],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_english_race.columns, new_column_names)}
diff_finetune_english_race = diff_finetune_english_race.rename(columns=column_mapping).transpose()

In [17]:
diff_finetune_english

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-0.013162,-0.017284,-0.002595,-0.022925,-0.056401,-0.024638,-0.072148,-0.024638,-0.007613,-0.017598
French,0.000004,0.015393,-0.003673,-0.013229,-0.045666,-0.018437,-0.039831,-0.026995,-0.011736,-0.014520
Spanish,0.008767,0.017988,-0.004926,-0.003325,-0.049798,0.022482,-0.087115,-0.012313,-0.007027,-0.031246
Greek,0.022018,-0.051560,0.073986,0.064805,0.003013,0.161584,-0.109113,0.044098,0.034852,-0.103102
Croatian,0.025692,0.030103,-0.018876,-0.008374,-0.007240,0.022245,-0.010135,0.034051,0.017369,-0.023297

In [18]:
diff_finetune_english_perc = (diff_finetune_english/df_pretrain)*100

In [19]:
diff_finetune_english_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-14.637002,-32.233023,-3.710713,-18.857524,-88.780675,-12.931607,-40.491160,-30.168309,-20.338781,-15.489917
French,0.005871,25.244306,-7.600488,-15.215711,-58.525652,-11.834590,-16.560753,-43.133763,-23.790659,-9.528042
Spanish,15.589353,30.859575,-10.282409,-4.130388,-57.208627,17.845174,-31.701351,-21.050534,-15.530527,-18.879636
Greek,33.745443,-42.463608,769.147152,111.329496,3.937969,132.914205,-37.297121,126.941887,89.197502,-56.942990
Croatian,34.475114,43.525228,-36.188721,-9.922101,-9.651923,14.130398,-4.155826,63.527019,58.019858,-14.569539

In [20]:
diff_finetune_english_perc_race = (diff_finetune_english_race/df_pretrain_race)*100

In [21]:
diff_finetune_english_perc_race

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263
French,-26.259805,-18.905554,-12.638724,-24.009131,-10.632214,-36.884109,3.371315,-33.541678,-22.828472,-4.337177
Spanish,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270
Greek,14.058024,14.058024,14.058024,14.058024,14.058024,14.058024,14.058024,14.058024,14.058024,14.058024
Croatian,6.153864,6.153864,6.153864,6.153864,6.153864,6.153864,6.153864,6.153864,6.153864,6.153864

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_english_perc.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_english_perc.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_english = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_english

           English    French   Spanish     Greek  Croatian
English   1.000000  0.769706  0.662415 -0.102478 -0.285893
French    0.769706  1.000000  0.848549 -0.244306 -0.209290
Spanish   0.662415  0.848549  1.000000 -0.130642  0.136292
Greek    -0.102478 -0.244306 -0.130642  1.000000 -0.150560
Croatian -0.285893 -0.209290  0.136292 -0.150560  1.000000

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_english_perc_race.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_english_perc_race.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_english_race = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_english_race

           English    French   Spanish     Greek  Croatian
English   1.000000  0.840442  1.000000 -1.000000 -1.000000
French    0.840442  1.000000  0.840442 -0.840442 -0.840442
Spanish   1.000000  0.840442  1.000000 -1.000000 -1.000000
Greek    -1.000000 -0.840442 -1.000000  1.000000  1.000000
Croatian -1.000000 -0.840442 -1.000000  1.000000  1.000000

In [24]:
row_index1 = 0
row_index2 = 1
row_index3 = 2
row_index4 = 3

# Get the rows as NumPy arrays
row1 = diff_finetune_english_perc.iloc[row_index1].values.reshape(1, -1)
row2 = diff_finetune_english_perc.iloc[row_index2].values.reshape(1, -1)
row3 = diff_finetune_english_perc.iloc[row_index3].values.reshape(1, -1)
row4 = diff_finetune_english_perc.iloc[row_index4].values.reshape(1, -1)

# Calculate the cosine similarity between the two rows
similarity = cosine_similarity(row1, row2)[0, 0]
similarity2 = cosine_similarity(row1, row3)[0, 0]
print("Similarity between english and french is:  ", similarity)
print("Similarity between english and spanish is:  ", similarity2)

Similarity between english and french is:   0.7697062897908824
Similarity between english and spanish is:   0.6624145106362409

## French Fine-tuning

In [25]:
## For French finetuning

english_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/french_finetune/emotion_profiles/english/"
french_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/french_finetune/emotion_profiles/french/"
spanish_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/french_finetune/emotion_profiles/spanish/"
greek_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/french_finetune/emotion_profiles/greek/"
croatian_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/french_finetune/emotion_profiles/croatian/"



english_finetune = find_emotions(english_path)
french_finetune = find_emotions(french_path)
spanish_finetune = find_emotions(spanish_path)
greek_finetune = find_emotions(greek_path)
croatian_finetune = find_emotions(croatian_path)

english_finetune = english_finetune.div(english_finetune.sum())
french_finetune = french_finetune.div(french_finetune.sum())
spanish_finetune = spanish_finetune.div(spanish_finetune.sum())
greek_finetune = greek_finetune.div(greek_finetune.sum())
croatian_finetune = croatian_finetune.div(croatian_finetune.sum())

In [26]:
# to obtain race

english_finetune_race = find_race(english_pretrain_path)
french_finetune_race = find_race(french_pretrain_path)
spanish_finetune_race = find_race(spanish_pretrain_path)
greek_finetune_race = find_race(greek_pretrain_path)
croatian_finetune_race = find_race(croatian_pretrain_path)

english_finetune_race = english_finetune_race.div(english_finetune_race.sum())
french_finetune_race = french_finetune_race.div(french_finetune_race.sum())
spanish_finetune_race = spanish_finetune_race.div(spanish_finetune_race.sum())
greek_finetune_race = greek_finetune_race.div(greek_finetune_race.sum())
croatian_finetune_race = croatian_finetune_race.div(croatian_finetune_race.sum())

In [27]:
english_diff = english_finetune - english_pretrain
french_diff = spanish_finetune-french_pretrain
spanish_diff = spanish_finetune-spanish_pretrain
greek_diff = greek_finetune-greek_pretrain
croatian_diff =  croatian_finetune- croatian_pretrain

In [28]:
# race diff

english_diff_race = english_finetune_race - english_pretrain_race
french_diff_race = spanish_finetune_race-french_pretrain_race
spanish_diff_race = spanish_finetune_race-spanish_pretrain_race
greek_diff_race = greek_finetune_race-greek_pretrain_race
croatian_diff_race =  croatian_finetune_race- croatian_pretrain_race

In [29]:
diff_finetune_french = pd.concat([english_diff, french_diff, spanish_diff, greek_diff, croatian_diff],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_french.columns, new_column_names)}
diff_finetune_french = diff_finetune_french.rename(columns=column_mapping).transpose()

In [30]:
# for race

diff_finetune_french_race = pd.concat([english_diff_race, french_diff_race, spanish_diff_race, greek_diff_race, croatian_diff_race],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_french_race.columns, new_column_names)}
diff_finetune_french_race = diff_finetune_french_race.rename(columns=column_mapping).transpose()

In [31]:
diff_finetune_french

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-0.072374,0.006651,-0.040248,-0.060246,-0.020403,-0.084447,0.041353,-0.031112,-0.029786,0.033647
French,-0.018143,-0.002562,0.003230,-0.007236,-0.044132,-0.033591,0.017428,0.002772,-0.030533,0.000914
Spanish,-0.008094,0.000624,0.003861,0.000206,-0.053862,-0.000016,-0.019749,0.007523,-0.025836,-0.013091
Greek,-0.004702,0.028663,0.028576,-0.001254,0.014283,0.022781,0.022040,0.043880,0.033972,0.017444
Croatian,-0.007274,0.041813,-0.007477,-0.015793,-0.007944,-0.010233,0.002377,0.022388,0.011187,0.065474

In [32]:
diff_finetune_french_perc = (diff_finetune_french/df_pretrain)*100

In [33]:
diff_finetune_french_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-80.483461,12.403154,-57.546461,-49.557804,-32.116999,-44.322880,23.208195,-38.095144,-79.574550,29.616847
French,-27.867583,-4.201576,6.684096,-8.323103,-56.559716,-21.561842,7.246046,4.428637,-61.893890,0.599475
Spanish,-14.392051,1.071295,8.058040,0.256310,-61.877485,-0.012845,-7.186854,12.862472,-57.101127,-7.909905
Greek,-7.206990,23.606009,297.069666,-2.154083,18.669040,18.738843,7.533748,126.316192,86.943943,9.634052
Croatian,-9.760943,60.456278,-14.334012,-18.712580,-10.589876,-6.500548,0.974674,41.767925,37.366946,40.945738

In [34]:
diff_finetune_french_perc_race = (diff_finetune_french_race/df_pretrain)*100

In [35]:
diff_finetune_french_perc_race

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-27.539611,-24.101578,-27.380197,-27.933394,-28.891196,-25.663161,-23.885953,-27.737997,-27.225000,-22.491823
French,-26.919417,-17.121200,-13.181931,-25.923164,-11.763386,-38.273351,3.180063,-36.634366,-23.695939,-3.965528
Spanish,-15.580195,-13.458528,-15.912714,-15.695309,-15.291447,-14.849588,-14.423307,-14.096247,-15.427255,-13.757577
Greek,15.858532,13.535935,16.315589,11.685696,15.171368,14.569832,13.991884,10.729540,12.093068,14.757488
Croatian,6.216801,5.904186,8.096890,6.816719,6.058312,6.559006,5.657136,5.656216,4.658075,6.099276

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_french_perc.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_french_perc.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_french = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_french

           English    French   Spanish     Greek  Croatian
English   1.000000  0.688005  0.462142 -0.546064  0.038831
French    0.688005  1.000000  0.929748 -0.132875 -0.144243
Spanish   0.462142  0.929748  1.000000 -0.071504 -0.140964
Greek    -0.546064 -0.132875 -0.071504  1.000000  0.181615
Croatian  0.038831 -0.144243 -0.140964  0.181615  1.000000

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_french_perc_race.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_french_perc_race.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_french_race = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_french_race

           English    French   Spanish     Greek  Croatian
English   1.000000  0.854960  0.998677 -0.987927 -0.989395
French    0.854960  1.000000  0.840976 -0.802496 -0.827752
Spanish   0.998677  0.840976  1.000000 -0.992276 -0.992158
Greek    -0.987927 -0.802496 -0.992276  1.000000  0.991794
Croatian -0.989395 -0.827752 -0.992158  0.991794  1.000000

In [38]:
row_index1 = 0
row_index2 = 1
row_index3 = 2
row_index4 = 3

# Get the rows as NumPy arrays
row1 = diff_finetune_french_perc.iloc[row_index1].values.reshape(1, -1)
row2 = diff_finetune_french_perc.iloc[row_index2].values.reshape(1, -1)
row3 = diff_finetune_french_perc.iloc[row_index3].values.reshape(1, -1)
row4 = diff_finetune_french_perc.iloc[row_index4].values.reshape(1, -1)

# Calculate the cosine similarity between the two rows
similarity = cosine_similarity(row1, row2)[0, 0]
similarity2 = cosine_similarity(row1, row3)[0, 0]
print("Similarity between english and french is:  ", similarity)
print("Similarity between english and spanish is:  ", similarity2)

Similarity between english and french is:   0.6880053181823973
Similarity between english and spanish is:   0.4621416760969459

## Greek Finetuning

In [39]:
## For Greek finetuning

english_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/greek_finetune/emotion_profiles/english/"
french_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/greek_finetune/emotion_profiles/french/"
spanish_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/greek_finetune/emotion_profiles/spanish/"
greek_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/greek_finetune/emotion_profiles/greek/"
croatian_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/greek_finetune/emotion_profiles/croatian/"



english_finetune = find_emotions(english_path)
french_finetune = find_emotions(french_path)
spanish_finetune = find_emotions(spanish_path)
greek_finetune = find_emotions(greek_path)
croatian_finetune = find_emotions(croatian_path)

english_finetune = english_finetune.div(english_finetune.sum())
french_finetune = french_finetune.div(french_finetune.sum())
spanish_finetune = spanish_finetune.div(spanish_finetune.sum())
greek_finetune = greek_finetune.div(greek_finetune.sum())
croatian_finetune = croatian_finetune.div(croatian_finetune.sum())

In [40]:
# to obtain race

english_finetune_race = find_race(english_pretrain_path)
french_finetune_race = find_race(french_pretrain_path)
spanish_finetune_race = find_race(spanish_pretrain_path)
greek_finetune_race = find_race(greek_pretrain_path)
croatian_finetune_race = find_race(croatian_pretrain_path)

english_finetune_race = english_finetune_race.div(english_finetune_race.sum())
french_finetune_race = french_finetune_race.div(french_finetune_race.sum())
spanish_finetune_race = spanish_finetune_race.div(spanish_finetune_race.sum())
greek_finetune_race = greek_finetune_race.div(greek_finetune_race.sum())
croatian_finetune_race = croatian_finetune_race.div(croatian_finetune_race.sum())

In [41]:

english_diff = english_finetune - english_pretrain
french_diff = spanish_finetune-french_pretrain
spanish_diff = spanish_finetune-spanish_pretrain
greek_diff = greek_finetune-greek_pretrain
croatian_diff =  croatian_finetune- croatian_pretrain

In [42]:
# race diff

english_diff_race = english_finetune_race - english_pretrain_race
french_diff_race = spanish_finetune_race-french_pretrain_race
spanish_diff_race = spanish_finetune_race-spanish_pretrain_race
greek_diff_race = greek_finetune_race-greek_pretrain_race
croatian_diff_race =  croatian_finetune_race- croatian_pretrain_race

In [43]:
diff_finetune_greek = pd.concat([english_diff, french_diff, spanish_diff, greek_diff, croatian_diff],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_greek.columns, new_column_names)}
diff_finetune_greek = diff_finetune_greek.rename(columns=column_mapping).transpose()

In [44]:
# for race

diff_finetune_greek_race = pd.concat([english_diff_race, french_diff_race, spanish_diff_race, greek_diff_race, croatian_diff_race],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_greek_race.columns, new_column_names)}
diff_finetune_greek_race = diff_finetune_greek_race.rename(columns=column_mapping).transpose()

In [45]:
diff_finetune_greek

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-0.062182,-0.013293,-0.029113,-0.071469,-0.012635,-0.034943,0.021125,-0.024945,-0.027116,-0.002394
French,-0.022508,0.012727,-0.026880,-0.009148,-0.032118,-0.047738,0.040251,0.010231,-0.035000,-0.001672
Spanish,-0.012459,0.015914,-0.026250,-0.001705,-0.041848,-0.014162,0.003074,0.014983,-0.030303,-0.015677
Greek,-0.010339,0.079205,0.043389,-0.007472,0.014461,0.021490,0.013082,0.041034,0.028246,-0.017415
Croatian,-0.017449,0.038673,-0.009540,-0.030974,0.005337,-0.029280,0.025806,0.008186,0.014799,0.088961

In [46]:
diff_finetune_greek_perc = (diff_finetune_greek/df_pretrain)*100

In [47]:
diff_finetune_greek_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-69.148880,-24.790032,-41.625757,-58.789565,-19.888546,-18.340419,11.855661,-30.544512,-72.440964,-2.107150
French,-34.571887,20.872473,-55.617887,-10.521721,-41.163249,-30.642098,16.735417,16.348013,-70.948257,-1.097369
Spanish,-22.153161,27.300989,-54.789365,-2.118376,-48.076262,-11.241692,1.118667,25.616080,-66.973045,-9.472388
Greek,-15.845350,65.231255,451.065603,-12.835437,18.901354,17.677318,4.471621,118.123318,72.290146,-9.618113
Croatian,-23.413638,55.915634,-18.290543,-36.700668,7.114343,-18.599609,10.581613,15.272486,49.434588,55.633528

In [48]:
diff_finetune_greek_perc_race = (diff_finetune_greek_race/df_pretrain_race)*100

In [49]:
diff_finetune_greek_perc_race

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263,-25.900263
French,-26.259805,-18.905554,-12.638724,-24.009131,-10.632214,-36.884109,3.371315,-33.541678,-22.828472,-4.337177
Spanish,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270,-14.651270
Greek,14.058024,14.058024,14.058024,14.058024,14.058024,14.058024,14.058024,14.058024,14.058024,14.058024
Croatian,6.153864,6.153864,6.153864,6.153864,6.153864,6.153864,6.153864,6.153864,6.153864,6.153864

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_greek_perc.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_greek_perc.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_greek = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_greek

           English    French   Spanish     Greek  Croatian
English   1.000000  0.726811  0.588040 -0.441616 -0.048008
French    0.726811  1.000000  0.956659 -0.503581  0.041829
Spanish   0.588040  0.956659  1.000000 -0.486918 -0.037586
Greek    -0.441616 -0.503581 -0.486918  1.000000  0.018146
Croatian -0.048008  0.041829 -0.037586  0.018146  1.000000

In [51]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_greek_perc_race.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_greek_perc_race.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_greek_race = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_greek_race

           English    French   Spanish     Greek  Croatian
English   1.000000  0.840442  1.000000 -1.000000 -1.000000
French    0.840442  1.000000  0.840442 -0.840442 -0.840442
Spanish   1.000000  0.840442  1.000000 -1.000000 -1.000000
Greek    -1.000000 -0.840442 -1.000000  1.000000  1.000000
Croatian -1.000000 -0.840442 -1.000000  1.000000  1.000000

In [52]:
row_index1 = 0
row_index2 = 1
row_index3 = 2
row_index4 = 3

# Get the rows as NumPy arrays
row1 = diff_finetune_greek_perc.iloc[row_index1].values.reshape(1, -1)
row2 = diff_finetune_greek_perc.iloc[row_index2].values.reshape(1, -1)
row3 = diff_finetune_greek_perc.iloc[row_index3].values.reshape(1, -1)
row4 = diff_finetune_greek_perc.iloc[row_index4].values.reshape(1, -1)

# Calculate the cosine similarity between the two rows
similarity = cosine_similarity(row1, row2)[0, 0]
similarity2 = cosine_similarity(row1, row3)[0, 0]
print("Similarity between english and french is:  ", similarity)
print("Similarity between english and spanish is:  ", similarity2)

Similarity between english and french is:   0.7268108263860713
Similarity between english and spanish is:   0.5880400294191218

## Spanish finetune

In [53]:
## For Spanish finetuning

english_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/spanish_finetune/emotion_profiles/english/"
french_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/spanish_finetune/emotion_profiles/french/"
spanish_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/spanish_finetune/emotion_profiles/spanish/"
greek_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/spanish_finetune/emotion_profiles/greek/"
croatian_path = "/Users/veljko/Desktop/atcs/atcs-project/MultiLingual_Stereotypes/out/spanish_finetune/emotion_profiles/croatian/"



english_finetune = find_emotions(english_path)
french_finetune = find_emotions(french_path)
spanish_finetune = find_emotions(spanish_path)
greek_finetune = find_emotions(greek_path)
croatian_finetune = find_emotions(croatian_path)

english_finetune = english_finetune.div(english_finetune.sum())
french_finetune = french_finetune.div(french_finetune.sum())
spanish_finetune = spanish_finetune.div(spanish_finetune.sum())
greek_finetune = greek_finetune.div(greek_finetune.sum())
croatian_finetune = croatian_finetune.div(croatian_finetune.sum())

In [54]:
# to obtain race

english_finetune_race = find_race(english_pretrain_path)
french_finetune_race = find_race(french_pretrain_path)
spanish_finetune_race = find_race(spanish_pretrain_path)
greek_finetune_race = find_race(greek_pretrain_path)
croatian_finetune_race = find_race(croatian_pretrain_path)

english_finetune_race = english_finetune_race.div(english_finetune_race.sum())
french_finetune_race = french_finetune_race.div(french_finetune_race.sum())
spanish_finetune_race = spanish_finetune_race.div(spanish_finetune_race.sum())
greek_finetune_race = greek_finetune_race.div(greek_finetune_race.sum())
croatian_finetune_race = croatian_finetune_race.div(croatian_finetune_race.sum())

In [55]:
english_diff = english_finetune - english_pretrain
french_diff = spanish_finetune-french_pretrain
spanish_diff = spanish_finetune-spanish_pretrain
greek_diff = greek_finetune-greek_pretrain
croatian_diff =  croatian_finetune- croatian_pretrain

In [56]:
# race diff

english_diff_race = english_finetune_race - english_pretrain_race
french_diff_race = spanish_finetune_race-french_pretrain_race
spanish_diff_race = spanish_finetune_race-spanish_pretrain_race
greek_diff_race = greek_finetune_race-greek_pretrain_race
croatian_diff_race =  croatian_finetune_race- croatian_pretrain_race

In [57]:
diff_finetune_spanish = pd.concat([english_diff, french_diff, spanish_diff, greek_diff, croatian_diff],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_spanish.columns, new_column_names)}
diff_finetune_spanish = diff_finetune_spanish.rename(columns=column_mapping).transpose()

In [58]:
# for race

diff_finetune_spanish_race = pd.concat([english_diff_race, french_diff_race, spanish_diff_race, greek_diff_race, croatian_diff_race],axis =1)
new_column_names = ["English", "French", "Spanish", "Greek", "Croatian"]
column_mapping = {old_name: new_name for old_name, new_name in zip(diff_finetune_spanish_race.columns, new_column_names)}
diff_finetune_spanish_race = diff_finetune_spanish_race.rename(columns=column_mapping).transpose()

In [59]:
diff_finetune_spanish

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-0.056782,-0.006726,-0.048496,-0.051074,-0.032356,-0.055230,0.033804,-0.027007,-0.023869,0.010769
French,-0.027351,0.008995,-0.003832,-0.028131,-0.047810,-0.083001,0.058215,-0.005232,-0.029596,0.045888
Spanish,-0.017302,0.012181,-0.003201,-0.020688,-0.057540,-0.049425,0.021038,-0.000480,-0.024899,0.031884
Greek,-0.019483,0.055150,0.003320,-0.007979,0.021515,0.002482,0.047732,0.029065,0.039115,0.034765
Croatian,0.007177,0.020700,0.004146,-0.021318,-0.013317,-0.007088,0.019489,-0.001259,0.007241,0.078746

In [60]:
diff_finetune_spanish_perc = (diff_finetune_spanish/df_pretrain)*100

In [61]:
diff_finetune_spanish_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-63.143745,-12.543121,-69.340154,-42.012791,-50.930812,-28.988178,18.971612,-33.068182,-63.766441,9.479226
French,-42.010976,14.751274,-7.928207,-32.355852,-61.273911,-53.277018,24.204350,-8.359668,-59.994311,30.111116
Spanish,-30.764881,20.897669,-6.682186,-25.701014,-66.103237,-39.232539,7.655811,-0.820880,-55.030029,19.264924
Greek,-29.860570,45.420611,34.514014,-13.707817,28.121665,2.041864,16.315784,83.669079,100.105957,19.200391
Croatian,9.630775,29.929374,7.949114,-25.259530,-17.752929,-4.502334,7.991506,-2.347965,24.187489,49.245366

In [62]:
diff_finetune_spanish_perc_race = (diff_finetune_spanish_race/df_pretrain)*100

In [63]:
diff_finetune_spanish_perc_race

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-27.539611,-24.101578,-27.380197,-27.933394,-28.891196,-25.663161,-23.885953,-27.737997,-27.225000,-22.491823
French,-26.919417,-17.121200,-13.181931,-25.923164,-11.763386,-38.273351,3.180063,-36.634366,-23.695939,-3.965528
Spanish,-15.580195,-13.458528,-15.912714,-15.695309,-15.291447,-14.849588,-14.423307,-14.096247,-15.427255,-13.757577
Greek,15.858532,13.535935,16.315589,11.685696,15.171368,14.569832,13.991884,10.729540,12.093068,14.757488
Croatian,6.216801,5.904186,8.096890,6.816719,6.058312,6.559006,5.657136,5.656216,4.658075,6.099276

In [64]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_spanish_perc.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_spanish_perc.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_spanish = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_spanish

           English    French   Spanish     Greek  Croatian
English   1.000000  0.810836  0.770410 -0.501972 -0.028386
French    0.810836  1.000000  0.973771 -0.297384  0.271501
Spanish   0.770410  0.973771  1.000000 -0.311471  0.255805
Greek    -0.501972 -0.297384 -0.311471  1.000000  0.415841
Croatian -0.028386  0.271501  0.255805  0.415841  1.000000

In [65]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a DataFrame called df with the given values
# Extract the language names as the index
languages = diff_finetune_spanish_perc_race.index.tolist()

# Calculate cosine similarity between every pair of languages
similarity_matrix = cosine_similarity(diff_finetune_spanish_perc_race.values)

# Create a DataFrame from the similarity matrix with language names as indices and columns
similarity_df_spanish_race = pd.DataFrame(similarity_matrix, index=languages, columns=languages)

# Print the similarity DataFrame
similarity_df_spanish_race

           English    French   Spanish     Greek  Croatian
English   1.000000  0.854960  0.998677 -0.987927 -0.989395
French    0.854960  1.000000  0.840976 -0.802496 -0.827752
Spanish   0.998677  0.840976  1.000000 -0.992276 -0.992158
Greek    -0.987927 -0.802496 -0.992276  1.000000  0.991794
Croatian -0.989395 -0.827752 -0.992158  0.991794  1.000000

In [66]:
row_index1 = 0
row_index2 = 1
row_index3 = 2
row_index4 = 3

# Get the rows as NumPy arrays
row1 = diff_finetune_spanish_perc.iloc[row_index1].values.reshape(1, -1)
row2 = diff_finetune_spanish_perc.iloc[row_index2].values.reshape(1, -1)
row3 = diff_finetune_spanish_perc.iloc[row_index3].values.reshape(1, -1)
row4 = diff_finetune_spanish_perc.iloc[row_index4].values.reshape(1, -1)

# Calculate the cosine similarity between the two rows
similarity = cosine_similarity(row1, row2)[0, 0]
similarity2 = cosine_similarity(row1, row3)[0, 0]
print("Similarity between english and french is:  ", similarity)
print("Similarity between english and spanish is:  ", similarity2)

Similarity between english and french is:   0.8108361185053057
Similarity between english and spanish is:   0.7704102901008076

## Analysis

### English Finetuning

In [67]:
diff_finetune_english_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-14.637002,-32.233023,-3.710713,-18.857524,-88.780675,-12.931607,-40.491160,-30.168309,-20.338781,-15.489917
French,0.005871,25.244306,-7.600488,-15.215711,-58.525652,-11.834590,-16.560753,-43.133763,-23.790659,-9.528042
Spanish,15.589353,30.859575,-10.282409,-4.130388,-57.208627,17.845174,-31.701351,-21.050534,-15.530527,-18.879636
Greek,33.745443,-42.463608,769.147152,111.329496,3.937969,132.914205,-37.297121,126.941887,89.197502,-56.942990
Croatian,34.475114,43.525228,-36.188721,-9.922101,-9.651923,14.130398,-4.155826,63.527019,58.019858,-14.569539

In [68]:
diff_finetune_english_perc.mean()

anger            13.835756
anticipation      4.986496
disgust         142.272964
fear             12.640754
joy             -42.045782
negative         28.024716
positive        -26.041242
sadness          19.223260
surprise         17.511478
trust           -23.082025
dtype: float64

In [69]:
diff_finetune_english_perc.loc[diff_finetune_english_perc.index != 'Greek'].mean()

anger            8.858334
anticipation    16.849022
disgust        -14.445583
fear           -12.031431
joy            -53.541719
negative         1.802344
positive       -23.227272
sadness         -7.706397
surprise        -0.410028
trust          -14.616783
dtype: float64

In [70]:
similarity_df_english

           English    French   Spanish     Greek  Croatian
English   1.000000  0.769706  0.662415 -0.102478 -0.285893
French    0.769706  1.000000  0.848549 -0.244306 -0.209290
Spanish   0.662415  0.848549  1.000000 -0.130642  0.136292
Greek    -0.102478 -0.244306 -0.130642  1.000000 -0.150560
Croatian -0.285893 -0.209290  0.136292 -0.150560  1.000000

### French Finetuning

In [71]:
diff_finetune_french_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-80.483461,12.403154,-57.546461,-49.557804,-32.116999,-44.322880,23.208195,-38.095144,-79.574550,29.616847
French,-27.867583,-4.201576,6.684096,-8.323103,-56.559716,-21.561842,7.246046,4.428637,-61.893890,0.599475
Spanish,-14.392051,1.071295,8.058040,0.256310,-61.877485,-0.012845,-7.186854,12.862472,-57.101127,-7.909905
Greek,-7.206990,23.606009,297.069666,-2.154083,18.669040,18.738843,7.533748,126.316192,86.943943,9.634052
Croatian,-9.760943,60.456278,-14.334012,-18.712580,-10.589876,-6.500548,0.974674,41.767925,37.366946,40.945738

In [72]:
diff_finetune_french_perc.mean()

anger          -27.942206
anticipation    18.667032
disgust         47.986266
fear           -15.698252
joy            -28.495007
negative       -10.731854
positive         6.355162
sadness         29.456016
surprise       -14.851735
trust           14.577241
dtype: float64

In [73]:
diff_finetune_french_perc.loc[diff_finetune_french_perc.index != 'Greek'].mean()

anger          -33.126010
anticipation    17.432288
disgust        -14.284584
fear           -19.084294
joy            -40.286019
negative       -18.099528
positive         6.060515
sadness          5.240972
surprise       -40.300655
trust           15.813039
dtype: float64

In [74]:
similarity_df_french

           English    French   Spanish     Greek  Croatian
English   1.000000  0.688005  0.462142 -0.546064  0.038831
French    0.688005  1.000000  0.929748 -0.132875 -0.144243
Spanish   0.462142  0.929748  1.000000 -0.071504 -0.140964
Greek    -0.546064 -0.132875 -0.071504  1.000000  0.181615
Croatian  0.038831 -0.144243 -0.140964  0.181615  1.000000

### Spanish Finetune

In [75]:
diff_finetune_spanish_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-63.143745,-12.543121,-69.340154,-42.012791,-50.930812,-28.988178,18.971612,-33.068182,-63.766441,9.479226
French,-42.010976,14.751274,-7.928207,-32.355852,-61.273911,-53.277018,24.204350,-8.359668,-59.994311,30.111116
Spanish,-30.764881,20.897669,-6.682186,-25.701014,-66.103237,-39.232539,7.655811,-0.820880,-55.030029,19.264924
Greek,-29.860570,45.420611,34.514014,-13.707817,28.121665,2.041864,16.315784,83.669079,100.105957,19.200391
Croatian,9.630775,29.929374,7.949114,-25.259530,-17.752929,-4.502334,7.991506,-2.347965,24.187489,49.245366

In [76]:
diff_finetune_spanish_perc.mean()

anger          -31.229879
anticipation    19.691161
disgust         -8.297484
fear           -27.807401
joy            -33.587845
negative       -24.791641
positive        15.027812
sadness          7.814477
surprise       -10.899467
trust           25.460205
dtype: float64

In [77]:
diff_finetune_spanish_perc.loc[diff_finetune_spanish_perc.index != 'Greek'].mean()

anger          -31.572207
anticipation    13.258799
disgust        -19.000358
fear           -31.332297
joy            -49.015222
negative       -31.500017
positive        14.705820
sadness        -11.149174
surprise       -38.650823
trust           27.025158
dtype: float64

In [78]:
similarity_df_spanish

           English    French   Spanish     Greek  Croatian
English   1.000000  0.810836  0.770410 -0.501972 -0.028386
French    0.810836  1.000000  0.973771 -0.297384  0.271501
Spanish   0.770410  0.973771  1.000000 -0.311471  0.255805
Greek    -0.501972 -0.297384 -0.311471  1.000000  0.415841
Croatian -0.028386  0.271501  0.255805  0.415841  1.000000

### Greek Finetune

In [79]:
diff_finetune_greek_perc

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
English,-69.148880,-24.790032,-41.625757,-58.789565,-19.888546,-18.340419,11.855661,-30.544512,-72.440964,-2.107150
French,-34.571887,20.872473,-55.617887,-10.521721,-41.163249,-30.642098,16.735417,16.348013,-70.948257,-1.097369
Spanish,-22.153161,27.300989,-54.789365,-2.118376,-48.076262,-11.241692,1.118667,25.616080,-66.973045,-9.472388
Greek,-15.845350,65.231255,451.065603,-12.835437,18.901354,17.677318,4.471621,118.123318,72.290146,-9.618113
Croatian,-23.413638,55.915634,-18.290543,-36.700668,7.114343,-18.599609,10.581613,15.272486,49.434588,55.633528

In [80]:
diff_finetune_greek_perc.mean()

anger          -33.026583
anticipation    28.906064
disgust         56.148410
fear           -24.193154
joy            -16.622472
negative       -12.229300
positive         8.952596
sadness         28.963077
surprise       -17.727506
trust            6.667702
dtype: float64

In [81]:
diff_finetune_greek_perc.loc[diff_finetune_greek_perc.index != 'Greek'].mean()

anger          -37.321892
anticipation    19.824766
disgust        -42.580888
fear           -27.032583
joy            -25.503429
negative       -19.705955
positive        10.072839
sadness          6.673017
surprise       -40.231920
trust           10.739155
dtype: float64

In [82]:
similarity_df_greek

           English    French   Spanish     Greek  Croatian
English   1.000000  0.726811  0.588040 -0.441616 -0.048008
French    0.726811  1.000000  0.956659 -0.503581  0.041829
Spanish   0.588040  0.956659  1.000000 -0.486918 -0.037586
Greek    -0.441616 -0.503581 -0.486918  1.000000  0.018146
Croatian -0.048008  0.041829 -0.037586  0.018146  1.000000